// export const mockEmails = [
//   {
//     id: 1,
//     sender: 'John Doe',
//     senderInitials: 'JD',
//     avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
//     subject: 'Weekly Team Meeting',
//     preview: 'Reminder about our weekly sync tomorrow at 10 AM',
//     time: '10:30 AM',
//     date: new Date().toISOString(),
//     label: 'Business',
//     isFavorite: false,
//     isRead: false,
//     isSpam: false,
//     isTrash: false,
//     isArchived: false,
//     isSent: false,
//     isDraft: false,
//     fromMe: false,
//     body: 'Hi team,\n\nJust a reminder that we have our weekly sync meeting tomorrow at 10 AM in the main conference room. Please bring your updates and blockers.\n\nBest regards,\nJohn',
//     hasAttachment: true
//   },
//   {
//     id: 2,
//     sender: 'Jane Smith',
//     senderInitials: 'JS',
//     avatar: 'https://randomuser.me/api/portraits/women/1.jpg',
//     subject: 'Project Update',
//     preview: 'Here are the latest updates on our current project',
//     time: 'Yesterday',
//     date: new Date(Date.now() - 86400000).toISOString(),
//     label: 'Team',
//     isFavorite: true,
//     isRead: true,
//     isSpam: false,
//     isTrash: false,
//     isArchived: false,
//     isSent: false,
//     isDraft: false,
//     fromMe: false,
//     body: 'Hello everyone,\n\nI wanted to share the latest progress on our project. We\'ve completed 75% of the tasks and are on track to meet our deadline.\n\nRegards,\nJane',
//     hasAttachment: false
//   },
//   {
//     id: 3,
//     sender: 'Marketing Team',
//     senderInitials: 'MT',
//     subject: 'New Campaign Ideas',
//     preview: 'Brainstorming session for the upcoming campaign',
//     time: 'Mar 15',
//     date: new Date(Date.now() - 172800000).toISOString(),
//     label: 'Management',
//     isFavorite: false,
//     isRead: false,
//     isSpam: false,
//     isTrash: false,
//     isArchived: true,
//     isSent: false,
//     isDraft: false,
//     fromMe: false,
//     body: 'Team,\n\nLet\'s schedule a brainstorming session for our Q2 marketing campaign. Please bring your ideas to the meeting.\n\nThanks,\nMarketing Team',
//     hasAttachment: true
//   },
//   {
//     id: 4,
//     sender: 'Support Team',
//     senderInitials: 'ST',
//     subject: 'Your recent support ticket',
//     preview: 'We have resolved your support ticket #45678',
//     time: '11:45 AM',
//     date: new Date().toISOString(),
//     label: 'Support',
//     isFavorite: false,
//     isRead: false,
//     isSpam: false,
//     isTrash: false,
//     isArchived: false,
//     isSent: false,
//     isDraft: false,
//     fromMe: false,
//     body: 'Dear User,\n\nWe are pleased to inform you that your support ticket #45678 has been resolved. Please let us know if you need any further assistance.\n\nBest regards,\nSupport Team',
//     hasAttachment: false
//   },
//   {
//     id: 5,
//     sender: 'HR Department',
//     senderInitials: 'HR',
//     subject: 'Important: Policy Updates',
//     preview: 'Please review the updated company policies',
//     time: '9:15 AM',
//     date: new Date().toISOString(),
//     label: 'HR',
//     isFavorite: false,
//     isRead: true,
//     isSpam: false,
//     isTrash: false,
//     isArchived: false,
//     isSent: false,
//     isDraft: false,
//     fromMe: false,
//     body: 'Hello Team,\n\nWe have updated several company policies. Please review them at your earliest convenience. The updated documents are attached.\n\nRegards,\nHR Department',
//     hasAttachment: true
//   }
// ];

// export const mockDrafts = [
//   {
//     id: 101,
//     sender: 'Me',
//     senderInitials: 'ME',
//     to: 'team@company.com',
//     subject: 'Project Timeline Update',
//     body: 'Hi team,\n\nI wanted to share an update on our project timeline...',
//     label: 'Business',
//     time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
//     date: new Date().toISOString(),
//     isDraft: true,
//     isFavorite: false,
//     isRead: true,
//     isSpam: false,
//     isTrash: false,
//     isArchived: false,
//     isSent: false,
//     fromMe: true,
//     hasAttachment: false,
//     preview: 'Hi team, I wanted to share an update on our project timeline...'
//   },
//   {
//     id: 102,
//     sender: 'Me',
//     senderInitials: 'ME',
//     to: 'client@example.com',
//     subject: 'Proposal Draft',
//     body: 'Dear Client,\n\nAttached please find our initial proposal for your review...',
//     label: 'Business',
//     time: 'Yesterday',
//     date: new Date(Date.now() - 86400000).toISOString(),
//     isDraft: true,
//     isFavorite: true,
//     isRead: true,
//     isSpam: false,
//     isTrash: false,
//     isArchived: false,
//     isSent: false,
//     fromMe: true,
//     hasAttachment: true,
//     preview: 'Dear Client, Attached please find our initial proposal...'
//   }
// ];





export const mockInboxEmails = [
  {
    id: 1,
    sender: 'John Doe',
    senderInitials: 'JD',
    subject: 'Weekly Team Meeting',
    preview: 'Reminder about our weekly sync tomorrow at 10 AM',
    time: '10:30 AM',
    date: new Date().toISOString(),
    label: 'Business',
    isFavorite: false,
    isRead: false,
    isSpam: false,
    isTrash: false,
    isArchived: false,
    isSent: false,
    isDraft: false,
    fromMe: false,
    body: 'Hi team,\n\nJust a reminder about our meeting...',
    hasAttachment: true
  },
  // Add more inbox emails...
];

export const mockSentEmails = [
  {
    id: 101,
    sender: 'Me',
    senderInitials: 'ME',
    subject: 'Project Update',
    preview: 'Here are the updates on our current project',
    time: 'Yesterday',
    date: new Date(Date.now() - 86400000).toISOString(),
    label: 'Team',
    isFavorite: false,
    isRead: true,
    isSpam: false,
    isTrash: false,
    isArchived: false,
    isSent: true,
    isDraft: false,
    fromMe: true,
    body: 'Hello team,\n\nHere are the updates...',
    hasAttachment: false
  },
  // Add more sent emails...
];

export const mockDrafts = [
  {
    id: 201,
    sender: 'Me',
    senderInitials: 'ME',
    to: 'team@company.com',
    subject: 'Draft: Project Timeline',
    body: 'Hi team,\n\nI wanted to share an update...',
    label: 'Business',
    time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    date: new Date().toISOString(),
    isDraft: true,
    isFavorite: false,
    isRead: true,
    isSpam: false,
    isTrash: false,
    isArchived: false,
    isSent: false,
    fromMe: true,
    hasAttachment: false,
    preview: 'Hi team, I wanted to share an update...'
  },
  // Add more drafts...
];