export const mockEmails = [
  {
    id: 1,
    sender: 'John Doe',
    senderInitials: 'JD',
    avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    subject: 'Weekly Team Meeting',
    preview: 'Reminder about our weekly sync tomorrow at 10 AM',
    time: '10:30 AM',
    date: new Date().toISOString(),
    label: 'Business',
    isFavorite: false,
    isRead: false,
    isSpam: false,
    isTrash: false,
    isArchived: false,
    isSent: false,
    isDraft: false,
    body: 'Hi team,\n\nJust a reminder that we have our weekly sync meeting tomorrow at 10 AM in the main conference room. Please bring your updates and blockers.\n\nBest regards,\nJohn',
    hasAttachment: true
  },
  {
    id: 2,
    sender: 'Jane Smith',
    senderInitials: 'JS',
    avatar: 'https://randomuser.me/api/portraits/women/1.jpg',
    subject: 'Project Update',
    preview: 'Here are the latest updates on our current project',
    time: 'Yesterday',
    date: new Date(Date.now() - 86400000).toISOString(),
    label: 'Team',
    isFavorite: true,
    isRead: true,
    isSpam: false,
    isTrash: false,
    isArchived: false,
    isSent: false,
    isDraft: false,
    body: 'Hello everyone,\n\nI wanted to share the latest progress on our project. We\'ve completed 75% of the tasks and are on track to meet our deadline.\n\nRegards,\nJane',
    hasAttachment: false
  },
  {
    id: 3,
    sender: 'Marketing Team',
    senderInitials: 'MT',
    subject: 'New Campaign Ideas',
    preview: 'Brainstorming session for the upcoming campaign',
    time: 'Mar 15',
    date: new Date(Date.now() - 172800000).toISOString(),
    label: 'Management',
    isFavorite: false,
    isRead: false,
    isSpam: false,
    isTrash: false,
    isArchived: true,
    isSent: false,
    isDraft: false,
    body: 'Team,\n\nLet\'s schedule a brainstorming session for our Q2 marketing campaign. Please bring your ideas to the meeting.\n\nThanks,\nMarketing Team',
    hasAttachment: true
  }
];

export const mockDrafts = [
  {
    id: 101,
    sender: 'Me',
    senderInitials: 'ME',
    to: 'team@company.com',
    subject: 'Project Timeline Update',
    body: 'Hi team,\n\nI wanted to share an update on our project timeline...',
    label: 'Business',
    time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    date: new Date().toISOString(),
    isDraft: true,
    isFavorite: false,
    isRead: true,
    isSpam: false,
    isTrash: false,
    isArchived: false,
    isSent: false,
    hasAttachment: false,
    preview: 'Hi team, I wanted to share an update on our project timeline...'
  }
];